### ISSUE TITLE
laravel_queue entered FATAL state

### ISSUE THREAD

**Issue by BruceYangMan** [Easter1021/docker_with_laravel_53#3]
can't running 
error log:
app         | 2016-08-31 09:17:13,127 INFO spawnerr: command at '/usr/local/bin/run_queue.sh' is not executable
app         | 2016-08-31 09:17:14,213 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
app         | 2016-08-31 09:17:14,213 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
app         | 2016-08-31 09:17:14,213 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
app         | 2016-08-31 09:17:14,214 INFO spawnerr: command at '/usr/local/bin/run_queue.sh' is not executable
app         | 2016-08-31 09:17:16,224 INFO spawnerr: command at '/usr/local/bin/run_queue.sh' is not executable
app         | 2016-08-31 09:17:19,240 INFO spawnerr: command at '/usr/local/bin/run_queue.sh' is not executable
app         | 2016-08-31 09:17:19,241 INFO gave up: laravel_queue entered FATAL state, too many start retries too quickly
^CGracefully stopping... (press Ctrl+C again to force)

docker-compose.yml
app:
  build: ./www
  container_name: app
  restart: always
  ports:
    - "80:80" # web
  links:
    - database:database
  volumes:
    - ./www:/var/www
database:
  build: ./database
  container_name: database
  restart: always
  ports:
    - "3306:3306"
  volumes:
    - ./store/database:/var/lib/mysql
  env_file:
    - .env

**Comment by Easter1021** [comment]
@BruceYangMan 

I was fix it up, and if you have and questions, please don't hesitate to contact me.

I look forward to hearing from you.

**Comment by GhulamJafar** [comment]
Hi bruce @BruceYangMan ,
I am having whm server and several hostings accounts. How can install supervisor on whm and provide access to all hosting accounts to user supervisor.

Thanks
